dist: trusty
sudo: required
language: php
php:
  - '7.1'
services:
  - docker
before_script:
  - bash app/scripts/build.sh
  - bash app/scripts/start.sh
  - bash app/scripts/init.sh
script:
  - bash app/scripts/test.sh
