<?php

namespace AppBundle\Repository;

/**
 * OrateurRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrateurRepository extends \Doctrine\ORM\EntityRepository
{
}
